package main

import (
    "log"
    "unicode/utf8"
);

type Game struct {
    id string,
    players []Player;
    tiles [][]Tile;
}

var MIN_NUMBER_OF_PLAYERS = 2
var MAX_NUMBER_OF_PLAYERS = 4
var DEFAULT_NUMBER_OF_LETTERS_IN_HAND = 7
var letterSet string;

func GetNewUUID() string {
    // Generate a new uuid for a new game.
    // Requires:
    // - The existance of a uuidgen binary installed on the machine
    // Guarantees
    // - Return a new uuid as generated by the called binary
    uuid, err := exec.Command("uuidgen").Output()
    if err != nil {
        log.Fatal(err)
    }
    return uuid
}

func PlayWord(word string, player Player)

func AddPlayer(playerName string, players *[]Player) {
    // Add a player to the list of players for the
    // upcoming game play

    if len(*players) >= MAX_NUMBER_OF_PLAYERS {
        log.Fatal("No more players can be added to the Game.")
    }

    player := Player{name: playerName}

    for i := 0; i < DEFAULT_NUMBER_OF_LETTERS_IN_HAND; i++ {
        player.lettersInHand += PopLetterFromSet()
    }

    *players = append(*players, player)

}

func PopLetterFromSet() string {
    // Pop the last letter (right end) from the
    // letter string. The letter will be returned and the
    // occurrence will be removed from the string.
    if len(letterSet) < 1 {
        log.Fatal("Cannot pop letter from set. Empty.")
    }
    var letterToReturn = string(letterSet[utf8.RuneCountInString(letterSet)-1])
    letterSet = letterSet[:len(letterSet)-1]
    return letterToReturn
}
